.TH HFIX∑ 6 2009-jun "linux" "interactive system usage and navigation"

.SH NAME
HFIX \- integrate gcc/make into my VIM/IDE to accelerate debugging

.SH PATRON (see HFIX (7) HERITAGE for more information)
hephaestus-klytotekhnes (blacksmith) olympian god of technology

.SH IMAGERY
muscular, lame-footed, usually shown seated with a hammer and an anvil

.SH SUMMARY (see HFIX (7) for more information)
HFIX (heatherly fix) is my VIM/IDE service to accelerate the painful,
repetitive, tedious, and error-prone cycle of compiling, linking,
debugging, and installing software into a more smooth and targeted one.

.SH SERIOUS FOREWARNING
i am a crazy, selfish, dog-fooding c-programmer.  my code tends to be
experimental and constantly evolving.  my point is NOT to be the best, it is
to challenge myself, build from scratch, and allow fast problem solving.

.SH TABLE OF CONTENTS
.nf  
a) overview        quick summary
b) sample          sample output (for yENV_audit)
c) table           sample of the table format
d) synopsis        function overview
e) preparing       intializing scoring
f) auditing        conducting audit on scoring table setup
g) marking         marking individual progress milestones
h) retrieving      pulling the scores back to host
i) reporting       helpers for titles and legends

.SH A) OVERVIEW
HFIX is a vim add-on which uses a combination of vim-script, c-program,
bash-script, and gcc/make to help automate my build, install, testing
with targeted and efary to use feedback.


HFIX∑gcc/make∑(----)∑∑chosen∑∑(w:wipe)∑=∑recon∑of∑files∑to∑be∑cleared∑∑∑∑∑∑∑∑∑∑∑(2.1a)∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑[?]
unit∑header∑∑∑∑∑1r∑∑-∑∑∑-∑  Å main∑src∑strp∑∑15r∑∑-∑∑∑-∑  Å temp∑files∑∑∑∑∑∑5r∑∑-∑∑∑-∑  Å                                                                    [?]
unit∑src∑∑∑∑∑∑∑13r∑∑-∑∑∑-∑  Å main∑obj∑∑∑∑∑∑∑15r∑∑-∑∑∑-∑  Å temp∑CAUTION∑∑∑∑1r∑∑-∑∑∑-∑  Å                                                                    [?]
unit∑src∑strp∑∑13r∑∑-∑∑∑-∑  Å main∑obj∑strp∑∑15r∑∑-∑∑∑-∑  Å swap∑CAUTION∑∑∑∑2r∑∑-∑∑∑-∑  Å                                                                    [?]
unit∑obj∑∑∑∑∑∑∑13r∑∑-∑∑∑-∑  Å main∑exec∑∑∑∑∑∑∑1r∑∑-∑∑∑-∑  Å HFIX∑working∑∑∑∑-∑∑∑-∑∑∑-∑  Å                                                                    [?]
unit∑obj∑strp∑∑13r∑∑-∑∑∑-∑  Å main∑debug∑∑∑∑∑∑1r∑∑-∑∑∑-∑  Å HTAG∑working∑∑∑∑-∑∑∑-∑∑∑-∑  Å                                                                    [?]
unit∑exec∑∑∑∑∑∑13r∑∑-∑∑∑-∑  Å main∑shared∑∑∑∑∑-∑∑∑-∑∑∑-∑  Å polymnia∑work∑∑∑1r∑∑-∑∑∑-∑  Å                                                                    [?]
unit∑debug∑∑∑∑∑13r∑∑-∑∑∑-∑  Å main∑static∑∑∑∑∑-∑∑∑-∑∑∑-∑  Å fat∑fingers∑∑∑∑∑-∑∑∑-∑∑∑-∑  Å                                                                    [?]
unit∑output∑∑∑∑∑1r∑∑-∑∑∑-∑  Å ∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑  Å ∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑∑  Å                                                                    [?]




HFIX is two-parted, a c-language program to interpret gcc, make, and linker
output, and vim-script for the main driver and interface with that c program,
the Makefile, and vim itself.

.SH B) DISPLAY


.SH BUGS ============================================================================#
HFIX is incredibly stable for me, but if anyone else used it it might explode
and take the universe with it.

.SH COLOPHON ]]======================================================================#
this page is part of a documentation package meant to make the use of the
heatherly tools easier and faster
