.TH HFIX· 6 2009-jun "linux" "interactive system usage and navigation"

.SH NAME
HFIX \- integrate gcc/make into my VIM/IDE to accelerate debugging

.SH PATRON (see HERITAGE at bottom for more)
hephaestus-klytotekhnes (blacksmith) olympian god of technology

.SH IMAGERY
muscular, lame-footed, usually shown seated with a hammer and an anvil

.SH SUMMARY (see HFIX (7) for more information)
HFIX (heatherly fix) is my VIM/IDE service to accelerate the painful,
repetitive, tedious, and error-prone cycle of compiling, linking,
debugging, and installing software into a more smooth and targeted one.

.SH SERIOUS FOREWARNING
i am a crazy, selfish, dog-fooding c-programmer.  my code tends to be
experimental and constantly evolving.  my point is NOT to be the best, it is
to challenge myself, build from scratch, and allow fast problem solving.

.SH TABLE OF CONTENTS
.nf  
a) overview        quick summary
b) sample          sample output (for yENV_audit)
c) table           sample of the table format
d) synopsis        function overview
e) preparing       intializing scoring
f) auditing        conducting audit on scoring table setup
g) marking         marking individual progress milestones
h) retrieving      pulling the scores back to host
i) reporting       helpers for titles and legends

.SH A) OVERVIEW
HFIX is two-parted, a c-language program to interpret gcc, make, and linker
output, and vim-script for the main driver and interface with that c program,
the Makefile, and vim itself.

.SH B) DISPLAY

